<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HW4Code</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="HW4Code_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW4Code_files/libs/quarto-html/quarto.js"></script>
<script src="HW4Code_files/libs/quarto-html/popper.min.js"></script>
<script src="HW4Code_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW4Code_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW4Code_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW4Code_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW4Code_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW4Code_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW4Code_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="HW4Code_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="HW4Code_files/libs/tabwid-1.1.3/tabwid.js"></script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW4Code</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<ol type="1">
<li>How does fish length predict fish weightfor trout perch (across all sample years)?</li>
</ol>
<p>Problem 1-</p>
<ol type="1">
<li>Null Hypothesis: There is no statistically significant relationship between the lengths of fish and their weight for trout perch.</li>
</ol>
<p>Alternative Hypothesis:There is a statistically significant relationship between the lengths of fish and their weight for trout perch.</p>
<p>This is the code to clean up the data provided by the data creators:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Package ID: knb-lter-ntl.6.34 Cataloging System:https://pasta.edirepository.org.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Data set title: North Temperate Lakes LTER: Fish Lengths and Weights 1981 - current.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Data set creator:  John Magnuson - University of Wisconsin-Madison </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Data set creator:  Stephen Carpenter - University of Wisconsin-Madison </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Data set creator:  Emily Stanley - University of Wisconsin-Madison </span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Metadata Provider:  NTL Information Manager - University of Wisconsin-Madison </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Contact:    -  NTL LTER  - ntl.infomgr@gmail.com</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Stylesheet v2.11 for metadata conversion into program: John H. Porter, Univ. Virginia, jporter@virginia.edu </span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>inUrl1  <span class="ot">&lt;-</span> <span class="st">"https://pasta.lternet.edu/package/data/eml/knb-lter-ntl/6/34/7dddb5e70250d2e24537e34272316220"</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>infile1 <span class="ot">&lt;-</span> <span class="fu">tempfile</span>()</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">try</span>(<span class="fu">download.file</span>(inUrl1,infile1,<span class="at">method=</span><span class="st">"curl"</span>))</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">is.na</span>(<span class="fu">file.size</span>(infile1))) <span class="fu">download.file</span>(inUrl1,infile1,<span class="at">method=</span><span class="st">"auto"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                   </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a> dt1 <span class="ot">&lt;-</span><span class="fu">read.csv</span>(infile1,<span class="at">header=</span>F </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>          ,<span class="at">skip=</span><span class="dv">1</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>            ,<span class="at">sep=</span><span class="st">","</span>  </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>                ,<span class="at">quot=</span><span class="st">'"'</span> </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        , <span class="at">col.names=</span><span class="fu">c</span>(</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"lakeid"</span>,     </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"year4"</span>,     </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"sampledate"</span>,     </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"gearid"</span>,     </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"spname"</span>,     </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"sampletype"</span>,     </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"depth"</span>,     </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"rep"</span>,     </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"indid"</span>,     </span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"length"</span>,     </span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"weight"</span>,     </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"sex"</span>,     </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"fishpart"</span>,     </span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"spseq"</span>,     </span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"flag"</span>    ), <span class="at">check.names=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>               </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="fu">unlink</span>(infile1)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix any interval or ratio columns mistakenly read in as nominal and nominal columns read as numeric or dates read as strings</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>lakeid)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>lakeid<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>lakeid)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>year4)<span class="sc">==</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>year4 <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt1<span class="sc">$</span>year4))[<span class="fu">as.integer</span>(dt1<span class="sc">$</span>year4) ]               </span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>year4)<span class="sc">==</span><span class="st">"character"</span>) dt1<span class="sc">$</span>year4 <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt1<span class="sc">$</span>year4)                                   </span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="co"># attempting to convert dt1$sampledate dateTime string to R date structure (date or POSIXct)                                </span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>tmpDateFormat<span class="ot">&lt;-</span><span class="st">"%Y-%m-%d"</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>tmp1sampledate<span class="ot">&lt;-</span><span class="fu">as.Date</span>(dt1<span class="sc">$</span>sampledate,<span class="at">format=</span>tmpDateFormat)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep the new dates only if they all converted correctly</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">length</span>(tmp1sampledate) <span class="sc">==</span> <span class="fu">length</span>(tmp1sampledate[<span class="sc">!</span><span class="fu">is.na</span>(tmp1sampledate)])){dt1<span class="sc">$</span>sampledate <span class="ot">&lt;-</span> tmp1sampledate } <span class="cf">else</span> {<span class="fu">print</span>(<span class="st">"Date conversion failed for dt1$sampledate. Please inspect the data and do the date conversion yourself."</span>)}                                                                    </span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(tmpDateFormat,tmp1sampledate) </span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>gearid)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>gearid<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>gearid)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>spname)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>spname<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>spname)</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>sampletype)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>sampletype<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>sampletype)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>depth)<span class="sc">==</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>depth <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt1<span class="sc">$</span>depth))[<span class="fu">as.integer</span>(dt1<span class="sc">$</span>depth) ]               </span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>depth)<span class="sc">==</span><span class="st">"character"</span>) dt1<span class="sc">$</span>depth <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt1<span class="sc">$</span>depth)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>rep)<span class="sc">==</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>rep <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt1<span class="sc">$</span>rep))[<span class="fu">as.integer</span>(dt1<span class="sc">$</span>rep) ]               </span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>rep)<span class="sc">==</span><span class="st">"character"</span>) dt1<span class="sc">$</span>rep <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt1<span class="sc">$</span>rep)</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>indid)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>indid<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>indid)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>length)<span class="sc">==</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>length <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt1<span class="sc">$</span>length))[<span class="fu">as.integer</span>(dt1<span class="sc">$</span>length) ]               </span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>length)<span class="sc">==</span><span class="st">"character"</span>) dt1<span class="sc">$</span>length <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt1<span class="sc">$</span>length)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>weight)<span class="sc">==</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>weight <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt1<span class="sc">$</span>weight))[<span class="fu">as.integer</span>(dt1<span class="sc">$</span>weight) ]               </span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>weight)<span class="sc">==</span><span class="st">"character"</span>) dt1<span class="sc">$</span>weight <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt1<span class="sc">$</span>weight)</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>sex)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>sex<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>sex)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>fishpart)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>fishpart<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>fishpart)</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>spseq)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>spseq<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>spseq)</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt1<span class="sc">$</span>flag)<span class="sc">!=</span><span class="st">"factor"</span>) dt1<span class="sc">$</span>flag<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt1<span class="sc">$</span>flag)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Missing Values to NA for non-dates</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="co"># Here is the structure of the input data frame:</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dt1)                            </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   349229 obs. of  15 variables:
 $ lakeid    : Factor w/ 11 levels "AL","BM","CB",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ year4     : int  1981 1981 1981 1981 1981 1981 1981 1981 1981 1981 ...
 $ sampledate: Date, format: "1981-08-04" "1981-08-04" ...
 $ gearid    : Factor w/ 17 levels "BSEINE","CRAYTR",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ spname    : Factor w/ 93 levels "BANDEDKILLIFISH",..: 6 6 6 6 6 6 6 6 6 6 ...
 $ sampletype: Factor w/ 13 levels ""," ","L","LG",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ depth     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
 $ rep       : int  4 4 4 4 4 4 2 2 1 1 ...
 $ indid     : Factor w/ 184621 levels "????A1","0001-003",..: 66483 66484 66485 66486 66487 66492 66256 66257 66196 66197 ...
 $ length    : int  42 41 46 26 21 240 100 98 85 107 ...
 $ weight    : num  NA NA NA NA NA 210 13 12 6.5 14 ...
 $ sex       : Factor w/ 7 levels "","0","B","F",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ fishpart  : Factor w/ 22 levels "","F","FM","FOM",..: 1 1 1 7 7 15 15 15 21 21 ...
 $ spseq     : Factor w/ 30438 levels " 12112000500",..: 438 438 438 438 438 438 402 402 395 395 ...
 $ flag      : Factor w/ 8 levels "","A","E","EH",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(dt1)                            </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The analyses below are basic descriptions of the variables. After testing, they should be replaced.                 </span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lakeid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   AL    BM    CB    CR    FI    ME    MO    SP    TB    TR    WI 
44202 37885  6381 35430 27076 28765 31300 37000  4715 51666 44809 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(year4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1981    1995    2004    2003    2012    2022 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sampledate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
"1981-07-28" "1995-08-28" "2004-07-26" "2003-08-29" "2012-07-23" "2022-08-31" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gearid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>BSEINE CRAYTR ELFISH FYKNED FYKNEL FYKNET MINNOW TRAMML    VGN VGN019 VGN025 
126869   2591  68962    818    727  77052   5544   8438   1583  17838  13832 
VGN032 VGN038 VGN051 VGN064 VGN089 VGN127 
  8921   8009   3668   2676   1700      1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spname)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   BANDEDKILLIFISH       BGPUMPHYBRID    BIGMOUTHBUFFALO      BLACKBULLHEAD 
                21                211                 78                181 
   BLACKCHINSHINER       BLACKCRAPPIE    BLACKNOSESHINER BLACKSTRPTOPMINNOW 
              4576               8786               2136                 16 
          BLUEGILL    BLUNTNOSEMINNOW             BOWFIN       BRASSYMINNOW 
             67940              18968                 85                 30 
   BROOKSILVERSIDE   BROOKSTICKLEBACK      BROWNBULLHEAD             BURBOT 
             17597                 16                140                112 
    CHANNELCATFISH              CISCO         COMMONCARP       COMMONSHINER 
               133              18389               1748               3139 
           CRAPPIE           CRAYFISH          CREEKCHUB             DARTER 
               316                  3                 13                 13 
     EMERALDSHINER      FANTAILDARTER            FATHEAD      FINESCALEDACE 
               122                 19                717                  4 
    FRESHWATERDRUM     GOLDENREDHORSE       GOLDENSHINER      GRASSPICKEREL 
               988                  8               8053                 48 
   GREATERREDHORSE      GREENBGHYBRID    GREENPUMPHYBRID       GREENSUNFISH 
                34                 36                942               1583 
             GUPPY      HORNYHEADCHUB         IOWADARTER       JOHNNYDARTER 
                 1                 51                722               2344 
         LAKETROUT      LAKEWHITEFISH     LARGEMOUTHBASS         LARVALFISH 
               244                332              15965                 28 
     LARVALSUNFISH           LOGPERCH     LONGEARSUNFISH        LONGNOSEGAR 
                10               1229                  5                188 
       MIMICSHINER     MOTTLEDSCULPIN          MUDMINNOW        MUSKELLUNGE 
             23037                568              11104                188 
   MUSKYPIKEHYBRID  NINESPSTICKLEBACK             NOFISH  NORTHERNHOGSUCKER 
                35                  7                  5                  1 
      NORTHERNPIKE      NREDBELLYDACE         PROPINQUUS        PUMPKINSEED 
               723                  1                 96               7927 
         QUILLBACK       RAINBOWSMELT           ROCKBASS     ROSYFACESHINER 
                 1              22645              13435                132 
          RUSTICUS   SHORTHEADREDHORS SHOVELNOSESTURGEON         SILVERPIKE 
                29                 46                  1                  1 
    SILVERREDHORSE       SLIMYSCULPIN     SMALLMOUTHBASS  SMALLMOUTHBUFFALO 
                 7                  7              10867                 10 
            SPLAKE      SPOTFINSHINER   SPOTTAILEMERALDH     SPOTTAILSHINER 
                 5                 82                  1                 74 
           SUNFISH         TROUTPERCH           UNIDCHUB         UNIDDARTER 
               236                489                  1                 11 
      UNIDENTIFIED         UNIDMINNOW       UNIDREDHORSE         UNIDSHINER 
                64                171                 13                 42 
           VIRILIS            WALLEYE           WARMOUTH          WHITEBASS 
                36               8289                  2               3032 
      WHITECRAPPIE        WHITESUCKER         YELLOWBASS     YELLOWBULLHEAD 
               961               4277                162               2176 
       YELLOWPERCH 
             59912 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sampletype)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   L     LG    LGR      M     M2      R     RM     SM    SMR 
 46855 240606     30   1060     71   4054     30  51510     30   3793     71 
   YOY   YOYR 
  1094     25 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(depth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
 -2.000  -1.000  -1.000   1.192  -1.000  35.000      23 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   2.000   3.000   4.494   6.000  30.000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(indid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2045-002 2045-003 2045-004 4052-002 8005-002 2041-001 2041-003 2041-004 
      22       22       22       22       22       21       21       21 
2045-005 2047-001 3041-001 4041-001 4041-002 4052-001 5001-001 5001-002 
      21       21       21       21       21       21       21       21 
5008-001 7019-001 7022-002 7022-003 8005-001 8005-004 1036-003 1036-004 
      21       21       21       21       21       21       20       20 
2041-002 2041-005 2041-006 2043-001 2045-001 2045-006 2045-007 2045-008 
      20       20       20       20       20       20       20       20 
4036-002 4036-003 4036-004 4036-005 4036-006 4041-003 4044-001 4046-001 
      20       20       20       20       20       20       20       20 
4047-001 4047-002 4047-003 4048-002 4048-003 4048-004 4051-002 4052-003 
      20       20       20       20       20       20       20       20 
4054-001 4054-003 5001-003 5001-004 5001-005 5001-006 5001-007 5001-008 
      20       20       20       20       20       20       20       20 
5007-003 5007-004 5008-002 5009-001 5021-001 6022-001 7018-001 7019-002 
      20       20       20       20       20       20       20       20 
7019-003 7019-004 7021-001 7021-002 7021-003 7021-004 7021-005 7022-001 
      20       20       20       20       20       20       20       20 
7022-004 8005-003 8010-001 8016-001 8016-002 9016-001 9023-001 9504-001 
      20       20       20       20       20       20       20       20 
0035-002 0042-001 0042-002 1036-002 1036-005 1040-001 1040-003 2039-001 
      19       19       19       19       19       19       19       19 
2039-002 2040-003 2042-001 2043-002 2044-001 2045-009 3003-001 3012-002 
      19       19       19       19       19       19       19       19 
3042-001 3042-002 4036-007  (Other) 
      19       19       19   347241 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    0.0    48.0    70.0   100.2   134.0  1250.0      69 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    0.0     3.2    22.0   154.7   104.0 12800.0  258087 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            0      B      F      I      M      S 
348336      7      1    398      4    481      2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fishpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            F     FM    FOM     FS     IS      K     KF     KS    KSF      M 
326079    304      1     11     11      1   2227     12     26      4    352 
    MK     MS     OM      S     SF    SFK    SFM    SFO   SFOM     SK     SM 
     1     34      1  19432    208     24      7     57    209     40    188 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spseq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>70211110-100 10391110-100 80221110-100 70191110-100 70161110-100 80161110-100 
         635          582          569          561          537          512 
30341110-100 70371110-100 80151110-100 10391120-100 50221110-100 80211110-100 
         490          486          480          456          446          433 
80171110-100 80051110-100 00321200-100 70171110-100 30450360-100 80241110-100 
         426          423          418          418          415          398 
80011110-100 70151110-100 70261110-100 10331200-100 50011110-100 80551110-100 
         397          391          388          381          375          375 
10391200-100 70181110-100 50151110-100 50231110-100 50131110-100 80021110-100 
         374          370          359          357          353          353 
00341210-100 10321200-100 30361110-100 50011050-100 00321110-100 00341200-100 
         348          345          343          341          339          337 
70301110-100 00351050-100 80251110-100 80071110-100 50141110-100 10381200-100 
         334          324          322          315          314          312 
00331110-100 30080360-100 50211110-100 50111110-100 70221110-100 80201110-100 
         308          307          305          302          299          285 
00391050-100 203902001600 70190950-100 50040390-100 203902001100 30440360-100 
         284          284          282          280          279          276 
50050390-100 203902001700 00331210-100 30381110-100 80081110-100 50231050-100 
         273          271          270          268          268          267 
10101200-100 40331200-100 95060220-100 80311110-100 80111110-100 80191110-100 
         265          265          264          261          260          259 
80341110-100 80371110-100 204002001100 30110360-100 10321210-100 10370340-100 
         259          259          256          255          254          253 
204002001200 30100360-100 203902001200 80231110-100 40381200-100 00361050-100 
         250          250          249          249          248          247 
80261110-100 40111200-100 40110360-100 70240950-100 80211115-100 00371050-100 
         247          245          242          241          241          238 
10341060-100 10361200-100 95030220-100 10330360-100 50091110-100 204002001700 
         237          237          237          235          235          234 
70341110-100 30020360-100 10031200-100 00341110-100 40011200-100 404401202200 
         234          233          231          230          228          227 
40561200-100  6551201-100 30410360-100      (Other) 
         227          225          225       317457 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flag) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            A      E     EH     ER      H      I      S 
348678    370     43      2     75     17     41      3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>                <span class="co"># Get more details on character variables</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>lakeid)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   AL    BM    CB    CR    FI    ME    MO    SP    TB    TR    WI 
44202 37885  6381 35430 27076 28765 31300 37000  4715 51666 44809 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>gearid)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>BSEINE CRAYTR ELFISH FYKNED FYKNEL FYKNET MINNOW TRAMML    VGN VGN019 VGN025 
126869   2591  68962    818    727  77052   5544   8438   1583  17838  13832 
VGN032 VGN038 VGN051 VGN064 VGN089 VGN127 
  8921   8009   3668   2676   1700      1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>spname)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   BANDEDKILLIFISH       BGPUMPHYBRID    BIGMOUTHBUFFALO      BLACKBULLHEAD 
                21                211                 78                181 
   BLACKCHINSHINER       BLACKCRAPPIE    BLACKNOSESHINER BLACKSTRPTOPMINNOW 
              4576               8786               2136                 16 
          BLUEGILL    BLUNTNOSEMINNOW             BOWFIN       BRASSYMINNOW 
             67940              18968                 85                 30 
   BROOKSILVERSIDE   BROOKSTICKLEBACK      BROWNBULLHEAD             BURBOT 
             17597                 16                140                112 
    CHANNELCATFISH              CISCO         COMMONCARP       COMMONSHINER 
               133              18389               1748               3139 
           CRAPPIE           CRAYFISH          CREEKCHUB             DARTER 
               316                  3                 13                 13 
     EMERALDSHINER      FANTAILDARTER            FATHEAD      FINESCALEDACE 
               122                 19                717                  4 
    FRESHWATERDRUM     GOLDENREDHORSE       GOLDENSHINER      GRASSPICKEREL 
               988                  8               8053                 48 
   GREATERREDHORSE      GREENBGHYBRID    GREENPUMPHYBRID       GREENSUNFISH 
                34                 36                942               1583 
             GUPPY      HORNYHEADCHUB         IOWADARTER       JOHNNYDARTER 
                 1                 51                722               2344 
         LAKETROUT      LAKEWHITEFISH     LARGEMOUTHBASS         LARVALFISH 
               244                332              15965                 28 
     LARVALSUNFISH           LOGPERCH     LONGEARSUNFISH        LONGNOSEGAR 
                10               1229                  5                188 
       MIMICSHINER     MOTTLEDSCULPIN          MUDMINNOW        MUSKELLUNGE 
             23037                568              11104                188 
   MUSKYPIKEHYBRID  NINESPSTICKLEBACK             NOFISH  NORTHERNHOGSUCKER 
                35                  7                  5                  1 
      NORTHERNPIKE      NREDBELLYDACE         PROPINQUUS        PUMPKINSEED 
               723                  1                 96               7927 
         QUILLBACK       RAINBOWSMELT           ROCKBASS     ROSYFACESHINER 
                 1              22645              13435                132 
          RUSTICUS   SHORTHEADREDHORS SHOVELNOSESTURGEON         SILVERPIKE 
                29                 46                  1                  1 
    SILVERREDHORSE       SLIMYSCULPIN     SMALLMOUTHBASS  SMALLMOUTHBUFFALO 
                 7                  7              10867                 10 
            SPLAKE      SPOTFINSHINER   SPOTTAILEMERALDH     SPOTTAILSHINER 
                 5                 82                  1                 74 
           SUNFISH         TROUTPERCH           UNIDCHUB         UNIDDARTER 
               236                489                  1                 11 
      UNIDENTIFIED         UNIDMINNOW       UNIDREDHORSE         UNIDSHINER 
                64                171                 13                 42 
           VIRILIS            WALLEYE           WARMOUTH          WHITEBASS 
                36               8289                  2               3032 
      WHITECRAPPIE        WHITESUCKER         YELLOWBASS     YELLOWBULLHEAD 
               961               4277                162               2176 
       YELLOWPERCH 
             59912 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>sampletype)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   L     LG    LGR      M     M2      R     RM     SM    SMR 
 46855 240606     30   1060     71   4054     30  51510     30   3793     71 
   YOY   YOYR 
  1094     25 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>indid)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2045-002 2045-003 2045-004 4052-002 8005-002 2041-001 2041-003 2041-004 
      22       22       22       22       22       21       21       21 
2045-005 2047-001 3041-001 4041-001 4041-002 4052-001 5001-001 5001-002 
      21       21       21       21       21       21       21       21 
5008-001 7019-001 7022-002 7022-003 8005-001 8005-004 1036-003 1036-004 
      21       21       21       21       21       21       20       20 
2041-002 2041-005 2041-006 2043-001 2045-001 2045-006 2045-007 2045-008 
      20       20       20       20       20       20       20       20 
4036-002 4036-003 4036-004 4036-005 4036-006 4041-003 4044-001 4046-001 
      20       20       20       20       20       20       20       20 
4047-001 4047-002 4047-003 4048-002 4048-003 4048-004 4051-002 4052-003 
      20       20       20       20       20       20       20       20 
4054-001 4054-003 5001-003 5001-004 5001-005 5001-006 5001-007 5001-008 
      20       20       20       20       20       20       20       20 
5007-003 5007-004 5008-002 5009-001 5021-001 6022-001 7018-001 7019-002 
      20       20       20       20       20       20       20       20 
7019-003 7019-004 7021-001 7021-002 7021-003 7021-004 7021-005 7022-001 
      20       20       20       20       20       20       20       20 
7022-004 8005-003 8010-001 8016-001 8016-002 9016-001 9023-001 9504-001 
      20       20       20       20       20       20       20       20 
0035-002 0042-001 0042-002 1036-002 1036-005 1040-001 1040-003 2039-001 
      19       19       19       19       19       19       19       19 
2039-002 2040-003 2042-001 2043-002 2044-001 2045-009 3003-001 3012-002 
      19       19       19       19       19       19       19       19 
3042-001 3042-002 4036-007  (Other) 
      19       19       19   347241 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>sex)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            0      B      F      I      M      S 
348336      7      1    398      4    481      2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>fishpart)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            F     FM    FOM     FS     IS      K     KF     KS    KSF      M 
326079    304      1     11     11      1   2227     12     26      4    352 
    MK     MS     OM      S     SF    SFK    SFM    SFO   SFOM     SK     SM 
     1     34      1  19432    208     24      7     57    209     40    188 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>spseq)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>70211110-100 10391110-100 80221110-100 70191110-100 70161110-100 80161110-100 
         635          582          569          561          537          512 
30341110-100 70371110-100 80151110-100 10391120-100 50221110-100 80211110-100 
         490          486          480          456          446          433 
80171110-100 80051110-100 00321200-100 70171110-100 30450360-100 80241110-100 
         426          423          418          418          415          398 
80011110-100 70151110-100 70261110-100 10331200-100 50011110-100 80551110-100 
         397          391          388          381          375          375 
10391200-100 70181110-100 50151110-100 50231110-100 50131110-100 80021110-100 
         374          370          359          357          353          353 
00341210-100 10321200-100 30361110-100 50011050-100 00321110-100 00341200-100 
         348          345          343          341          339          337 
70301110-100 00351050-100 80251110-100 80071110-100 50141110-100 10381200-100 
         334          324          322          315          314          312 
00331110-100 30080360-100 50211110-100 50111110-100 70221110-100 80201110-100 
         308          307          305          302          299          285 
00391050-100 203902001600 70190950-100 50040390-100 203902001100 30440360-100 
         284          284          282          280          279          276 
50050390-100 203902001700 00331210-100 30381110-100 80081110-100 50231050-100 
         273          271          270          268          268          267 
10101200-100 40331200-100 95060220-100 80311110-100 80111110-100 80191110-100 
         265          265          264          261          260          259 
80341110-100 80371110-100 204002001100 30110360-100 10321210-100 10370340-100 
         259          259          256          255          254          253 
204002001200 30100360-100 203902001200 80231110-100 40381200-100 00361050-100 
         250          250          249          249          248          247 
80261110-100 40111200-100 40110360-100 70240950-100 80211115-100 00371050-100 
         247          245          242          241          241          238 
10341060-100 10361200-100 95030220-100 10330360-100 50091110-100 204002001700 
         237          237          237          235          235          234 
70341110-100 30020360-100 10031200-100 00341110-100 40011200-100 404401202200 
         234          233          231          230          228          227 
40561200-100  6551201-100 30410360-100      (Other) 
         227          225          225       317457 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.factor</span>(dt1<span class="sc">$</span>flag))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            A      E     EH     ER      H      I      S 
348678    370     43      2     75     17     41      3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(dt1)               </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>fishlengths<span class="ot">&lt;-</span>dt1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fishlengths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  lakeid year4 sampledate gearid       spname sampletype depth rep indid length
1     AL  1981 1981-08-04 BSEINE BLACKCRAPPIE               -1   4 321M1     42
2     AL  1981 1981-08-04 BSEINE BLACKCRAPPIE               -1   4 321M2     41
3     AL  1981 1981-08-04 BSEINE BLACKCRAPPIE               -1   4 321M3     46
4     AL  1981 1981-08-04 BSEINE BLACKCRAPPIE               -1   4 321M4     26
5     AL  1981 1981-08-04 BSEINE BLACKCRAPPIE               -1   4 321M5     21
6     AL  1981 1981-08-04 BSEINE BLACKCRAPPIE               -1   4 321R1    240
  weight sex fishpart        spseq flag
1     NA               3211010-100     
2     NA               3211010-100     
3     NA               3211010-100     
4     NA            K  3211010-100     
5     NA            K  3211010-100     
6    210            S  3211010-100     </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#installing packages</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># general usage</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.1     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here) <span class="co"># organization</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Spring 23/ES 193DS/Homework4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly) <span class="co"># interactive plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'plotly'

The following object is masked from 'package:ggplot2':

    last_plot

The following object is masked from 'package:stats':

    filter

The following object is masked from 'package:graphics':

    layout</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr) <span class="co"># quick glimpses at data</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar) <span class="co"># visualizing missing data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'naniar'

The following object is masked from 'package:skimr':

    n_complete</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magick) <span class="co"># inserting images into plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to ImageMagick 6.9.12.3
Enabled features: cairo, freetype, fftw, ghostscript, heic, lcms, pango, raw, rsvg, webp
Disabled features: fontconfig, x11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(NatParksPalettes) <span class="co"># one example of color palette package</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wesanderson) <span class="co"># another example of a color palette package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'wesanderson':
  method        from            
  print.palette NatParksPalettes</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co"># putting plots together</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'flextable'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:plotly':

    highlight, style</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    compose</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
</div>
<p>#2 code)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating filtered data frame</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the columns you want to keep</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>length_wt_yr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"year4"</span>, <span class="st">"length"</span>, <span class="st">"weight"</span>)</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data table to include only the specified columns</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> fishlengths <span class="sc">%&gt;%</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(length_wt_yr))</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(filtered_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#visuaization of the missing data for the filtered dataset</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(filtered_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW4Code_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>#2 answer) a) The missing data is relevant to our hypothesis because there are several missing data points for weight which could alter the results. However, the 500+ data points we can reference should be good enough to test our hypothesis.</p>
<p>#3 code)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#removing rows with NA data</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>complete_data<span class="ot">&lt;-</span> filtered_data[<span class="fu">complete.cases</span>(filtered_data),]</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(complete_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#exploring the relationship visually</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> complete_data, <span class="fu">aes</span>(<span class="at">x =</span> length, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW4Code_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear regression test</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>lmlength_mass<span class="ot">&lt;-</span> <span class="fu">lm</span>(weight<span class="sc">~</span>length, <span class="at">data=</span> complete_data)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co">#show results</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmlength_mass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight ~ length, data = complete_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-1661.7  -142.1    -6.5   118.8 10385.8 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -309.55373    1.60785  -192.5   &lt;2e-16 ***
length         3.00965    0.00814   369.7   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 303 on 91088 degrees of freedom
Multiple R-squared:  0.6001,    Adjusted R-squared:  0.6001 
F-statistic: 1.367e+05 on 1 and 91088 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>#4 code)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating diagnostic plots to visually check assumptions</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lmlength_mass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW4Code_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>#5 answer)</p>
<p>RvF- The residuals are not evenly and randomly distributed, so the assumption of homoscedasticity is violated.</p>
<p>S-L: These residuals are not evenly and randomly distributed as well, so the assumption of homoscedasticity is violated.</p>
<p>Q-Q: These residuals are not normally distribute because they do not follow the straight trend line.</p>
<p>RvL- These residuals show that outliers largely affect the data and that the assumption of homoscedasticity is violated.</p>
<p>We can infer that the residuals are not linear and that the data is heteroscedastic so the linear regression is not a good predictor of values.</p>
<p>#6 code)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary of linear regression</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmlength_mass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight ~ length, data = complete_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-1661.7  -142.1    -6.5   118.8 10385.8 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -309.55373    1.60785  -192.5   &lt;2e-16 ***
length         3.00965    0.00814   369.7   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 303 on 91088 degrees of freedom
Multiple R-squared:  0.6001,    Adjusted R-squared:  0.6001 
F-statistic: 1.367e+05 on 1 and 91088 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#this summary shows a strong relationship between predictor and response. high r squared indicates good fit. intercept and length coefficients statistically significant</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating table to summarize anova table</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>model_summary<span class="ot">&lt;-</span><span class="fu">summary</span>(lmlength_mass)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="co">#storing anova table as object</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>model_squares<span class="ot">&lt;-</span> <span class="fu">anova</span>(lmlength_mass)</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>model_squares</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: weight
             Df     Sum Sq    Mean Sq F value    Pr(&gt;F)    
length        1 1.2549e+10 1.2549e+10  136700 &lt; 2.2e-16 ***
Residuals 91088 8.3620e+09 9.1802e+04                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>model_squares_table<span class="ot">&lt;-</span><span class="fu">tidy</span>(model_squares) <span class="sc">%&gt;%</span> </span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># round the sum of squares and mean squares columns </span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(sumsq<span class="sc">:</span>meansq, <span class="sc">~</span> <span class="fu">round</span>(.x, <span class="at">digits =</span> <span class="dv">5</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># round the F-statistic </span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">statistic =</span> <span class="fu">round</span>(statistic, <span class="at">digits =</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># replace the small p value with &lt; 0.001</span></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p.value =</span> <span class="fu">case_when</span>(</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>    p.value <span class="sc">&lt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">"&lt; 0.001"</span></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span> </span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rename length to be more meaningful</span></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">term =</span> <span class="fu">case_when</span>(</span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a>    term <span class="sc">==</span> <span class="st">"length"</span> <span class="sc">~</span> <span class="st">"Length (mm)"</span>,</span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a>    term <span class="sc">==</span> <span class="st">"weight"</span> <span class="sc">~</span> <span class="st">"Weight (g)"</span>,</span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> term</span>
<span id="cb88-15"><a href="#cb88-15" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span> </span>
<span id="cb88-16"><a href="#cb88-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make the data frame a flextable object</span></span>
<span id="cb88-17"><a href="#cb88-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">flextable</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb88-18"><a href="#cb88-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># change the header labels to be meaningful</span></span>
<span id="cb88-19"><a href="#cb88-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">df =</span> <span class="st">"Degrees of Freedom"</span>, </span>
<span id="cb88-20"><a href="#cb88-20" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sumsq =</span> <span class="st">"Sum of squares"</span>,</span>
<span id="cb88-21"><a href="#cb88-21" aria-hidden="true" tabindex="-1"></a>                    <span class="at">meansq =</span> <span class="st">"Mean squares"</span>,</span>
<span id="cb88-22"><a href="#cb88-22" aria-hidden="true" tabindex="-1"></a>                    <span class="at">statistic =</span> <span class="st">"F-statistic"</span>,</span>
<span id="cb88-23"><a href="#cb88-23" aria-hidden="true" tabindex="-1"></a>                    <span class="at">p.value =</span> <span class="st">"p-value"</span>)</span>
<span id="cb88-24"><a href="#cb88-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-25"><a href="#cb88-25" aria-hidden="true" tabindex="-1"></a>model_squares_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div class="tabwid"><style>.cl-9e4ff5b8{}.cl-9e448368{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9e4902da{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9e4902e4{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9e491ed2{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9e491edc{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9e491ee6{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9e491ee7{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9e491ef0{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9e491ef1{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-9e4ff5b8"><thead><tr style="overflow-wrap:break-word;"><th class="cl-9e491ed2"><p class="cl-9e4902da"><span class="cl-9e448368">term</span></p></th><th class="cl-9e491edc"><p class="cl-9e4902e4"><span class="cl-9e448368">Degrees of Freedom</span></p></th><th class="cl-9e491edc"><p class="cl-9e4902e4"><span class="cl-9e448368">Sum of squares</span></p></th><th class="cl-9e491edc"><p class="cl-9e4902e4"><span class="cl-9e448368">Mean squares</span></p></th><th class="cl-9e491edc"><p class="cl-9e4902e4"><span class="cl-9e448368">F-statistic</span></p></th><th class="cl-9e491ed2"><p class="cl-9e4902da"><span class="cl-9e448368">p-value</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-9e491ee6"><p class="cl-9e4902da"><span class="cl-9e448368">Length (mm)</span></p></td><td class="cl-9e491ee7"><p class="cl-9e4902e4"><span class="cl-9e448368">1</span></p></td><td class="cl-9e491ee7"><p class="cl-9e4902e4"><span class="cl-9e448368">12,549,293,413</span></p></td><td class="cl-9e491ee7"><p class="cl-9e4902e4"><span class="cl-9e448368">12,549,293,413.06</span></p></td><td class="cl-9e491ee7"><p class="cl-9e4902e4"><span class="cl-9e448368">136,700.2</span></p></td><td class="cl-9e491ee6"><p class="cl-9e4902da"><span class="cl-9e448368">&lt; 0.001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9e491ef0"><p class="cl-9e4902da"><span class="cl-9e448368">Residuals</span></p></td><td class="cl-9e491ef1"><p class="cl-9e4902e4"><span class="cl-9e448368">91,088</span></p></td><td class="cl-9e491ef1"><p class="cl-9e4902e4"><span class="cl-9e448368">8,362,023,669</span></p></td><td class="cl-9e491ef1"><p class="cl-9e4902e4"><span class="cl-9e448368">91,801.59</span></p></td><td class="cl-9e491ef1"><p class="cl-9e4902e4"><span class="cl-9e448368"></span></p></td><td class="cl-9e491ef0"><p class="cl-9e4902da"><span class="cl-9e448368"></span></p></td></tr></tbody></table></div>
</div>
</div>
<p>#8 answer)</p>
<p>The information of the anova table suggests similar information to the summary table. It shows a strong correlation between the predictor and response, however the low p-value suggests that the null hypothesis should be rejected</p>
<p>#9 answer)</p>
<p>The linear regression revealed a significant direct relationship between the weight of the plants and their length (coefficient estimate= 3.00965, t(91088) = 369.7, p &lt; 2e-16). The model accounted for a substantial amount of the variability in weight (R² = 0.6001), which was supported by the highly significant F-statistic (F(1, 91088) = 1.367e+05. These findings suggest that length is a strong predictor of weight, but there is a high variance in the data.</p>
<p>#10 code)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract model predictions using ggpredict</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(lmlength_mass, <span class="at">terms =</span> <span class="st">"length"</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Predicted values of weight

length | Predicted |             95% CI
---------------------------------------
     0 |   -309.55 | [-312.71, -306.40]
   200 |    292.38 | [ 290.28,  294.47]
   300 |    593.34 | [ 590.29,  596.39]
   500 |   1195.27 | [1189.41, 1201.13]
   700 |   1797.20 | [1788.27, 1806.13]
   800 |   2098.16 | [2087.68, 2108.65]
  1000 |   2700.09 | [2686.46, 2713.73]
  1300 |   3602.99 | [3584.60, 3621.37]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>plot_predictions <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> complete_data, </span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">aes</span>(<span class="at">x =</span> length, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># first plot the underlying data from maples_data</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># then plot the predictions</span></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> predictions, </span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> predicted), </span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># then plot the 95% confidence interval from ggpredict</span></span>
<span id="cb91-10"><a href="#cb91-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> predictions, </span>
<span id="cb91-11"><a href="#cb91-11" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> predicted, <span class="at">ymin =</span> <span class="sc">-</span><span class="dv">312</span>, <span class="at">ymax =</span> <span class="dv">3621</span>), </span>
<span id="cb91-12"><a href="#cb91-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb91-13"><a href="#cb91-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># theme and meaningful labels</span></span>
<span id="cb91-14"><a href="#cb91-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb91-15"><a href="#cb91-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Length (mm)"</span>,</span>
<span id="cb91-16"><a href="#cb91-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Weight (g)"</span>)</span>
<span id="cb91-17"><a href="#cb91-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-18"><a href="#cb91-18" aria-hidden="true" tabindex="-1"></a>plot_predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW4Code_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#the CI was not showing on the graph so I manually input the data which does not display them quite correctly but gives an idea of the CI</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="a">
<li>This plot shows the predicted weight value based on the length value with the blue line. The filtered data is plotted on this to show how it compares to the predicted values. The grey area is the confidence interval and the mean of the values is expected to fall within this.</li>
</ol>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>